# Generated by Django 4.2.3 on 2024-01-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='В работе', max_length=255),
        ),
    ]
